# Generated by Django 3.2.18 on 2023-05-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
